### ISSUE TITLE
Unable to access the tinymce object 

### ISSUE THREAD

**Issue by deshartman** [tinymce/tinymce-svelte#29]
Hi,

I'm fairly new to TinyMCE and to using it in Svelte, but it I cannot find a way to access tinymce using this wrapper. What I am trying to do is build a plugin as per [this](https://www.tiny.cloud/blog/slash-commands-rich-text-editor/) blog.

In the blog they reference the script library tinymce in the header, but this Svelte wrapper does not expose that in <script>. I even tried onMount(). How do I access tinymce using this wrapper, specifically "tinymce.PluginManager.add(" ?

```
  import Editor from "@tinymce/tinymce-svelte";
  import { onMount } from "svelte";

  onMount(() => {
    console.log(`tinymce: ${tinymce}`);  // UNDEFINED
  });

  let conf = {
    toolbar: "undo redo  image table",
    menubar: true,
    selector: "textarea",
  };
</script>

<main>
  <Editor scriptSrc="../../node_modules/tinymce/tinymce.min.js" apiKey={tinyAPIKey} {conf} />
</main>
```

Here is the code snippet from the Plugin, I am trying to put in <script>. Editor replace tinymce.init, but how do I access tinymcce.PluginManager........

```
tinymce.PluginManager.add('slashcommands', function (editor) {
    var insertActions = [
        {
            text: 'Heading 1',
            icon: 'h1',
            action: function () {
                editor.execCommand('mceInsertContent', false, '<h1>Heading 1</h1>')
                editor.selection.select(editor.selection.getNode());
            }
        }
    ];

    // Register the slash commands autocompleter
    editor.ui.registry.addAutocompleter('slashcommands', {
        ch: '/',
        minChars: 0,
        columns: 1,
        fetch: function (pattern) {
            const matchedActions = insertActions.filter(function (action) {
                return action.type === 'separator' ||
                    action.text.toLowerCase().indexOf(pattern.toLowerCase()) !== -1;
            });

            return new Promise((resolve) => {
                var results = matchedActions.map(function (action) {
                    return {
                        meta: action,
                        text: action.text,
                        icon: action.icon,
                        value: action.text,
                        type: action.type
                    }
                });
                resolve(results);
            });
        },
        onAction: function (autocompleteApi, rng, action, meta) {
            editor.selection.setRng(rng);
            // Some actions don't delete the "slash", so we delete all the slash
            // command content before performing the action
            editor.execCommand('Delete');
            meta.action();
            autocompleteApi.hide(); 
        }
    });
    return {};
});

tinymce.init({
    selector: "textarea",
    plugins: "slashcommands lists",
    height: 400,
});
```

**Comment by jscasca** [comment]
hey @deshartman , the svelte wrapper will just create an instance of the TinyMCE editor. When creating a new instance, the wrapper will try to find the global TinyMCE object (`tinymce`), if it can't find that it will fall back to downloading a new tinymce script and creating a global `tinymce` object. Your console log is not showing anything because at mount there is no global `tinymce` instance.

An easy way to sort this out is by copying your tinymce folder to your public folder and importing your own tinymce script in the `index.html` entry point of your app to ensure that editor instances will have access to a global `tinymce` object. By loading the tinymce script in your index you'll have access to the PluginManager.

Finally, in your `<Editor {conf} />` component you can use the plugin you added via the PluginManager

Hope this helps

**Comment by deshartman** [comment]
@jscasca Thank you for coming back to me. I have done what you suggested and tinymce is now available on mount. 

I also imported the local tinymce in App.svelte
```
<script>
  import { onMount } from "svelte";
  import Editor from "@tinymce/tinymce-svelte";
  import tinymce from "tinymce/tinymce.min.js";

  onMount(() => {
    console.log(`App mounted: ${tinymce}`);
  });
</script>

<main>
  <h1>Hello Tiny</h1>
  <Editor />
</main>

```
Although the onMount is fine, it did not display and had errors:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/47675451/209233625-015831ed-6473-4ade-9c4f-2a7bb5f34689.png">


I would like to still clarify if there is a better way to do this? As I understand it, if you pass in a value for "scriptSrc" on Editor, it picks up the local copy on tinymce, so why can this not be exposed, rather than relying on index.html script? could you expose the tinymce in Editor like this? Just seems like a neat way to do it all in Svelte, rather than fiddling with header scripts.

```
<script>
  import { onMount } from "svelte";
  import Editor from "@tinymce/tinymce-svelte";

  onMount(() => {
    console.log(`App mounted: ${Editor.tinymce}`);
  });
</script>

<main>
  <h1>Hello Tiny</h1>
  <Editor scriptSrc="tinymce/tinymce.min.js" />
</main>

```

**Comment by jscasca** [comment]
If you choose to go the `import` route you'll have more headaches than it's worth. I rather recommend the index approach.

If you go the `import` route, you'll have to bundle all its libraries. That means all the plugins, skins, themes, and the sort. Otherwise it will complain about not finding the resources (as your screenshot).

The `tinymce-svelte` does expose the `tinymce` object but only after it has been initialised. The reason for this is that you don't know at what point the svelte app will create the component. With this in mind you should be able to create the plugin for your instance during the setup of the editor (I'll try to create a sample for this during the weekend).

The `scriptSrc` property is used to select where to download a tinymce script in case there is no `tinymce` object available at runtime. So basically it goes like this: is there a `tinymce` object? Then load it, otherwise: do you have a script src? Then download from it, otherwise download from the default cdn

**Comment by deshartman** [comment]
Perfect, thanks. Looking forward to the example. Just trying to get my head around this ;-)

**Comment by dmccallie** [comment]
Hello @jscasca, this is very timely for me as well - I look forward to your example!

In my case, I'd like to enable svelte-based inline-editing as per the example at https://www.tiny.cloud/docs/general-configuration-guide/use-tinymce-inline/

Those examples all depend on calling  `tinymce.init(someConfig);`  which I can't figure out how to do when using the svelte Editor component.  (I am importing the tinymce code via the Editor's  `scriptSrc="/tinymce/tinymce.min.js"` from my public directory, which works fine for the regular iFrame mode.)

**Comment by jscasca** [comment]
@deshartman  I made a quick sample of how to add a plugin in the `setup` phase of the wrapper. As I was mentioning before, the wrapper will look for TinyMCE instances and if it can;t find one it will download a new tinymce script from the `scriptSrc` or from the Tiny CDN by default. After downloading the `tinymce` script, you will have the `tinymce` object available before the editor is created.

```
<script>
  import Editor from '@tinymce/tinymce-svelte';
	export let name;

  const pluginName = 'MyCustomPlugin';

  // The custom "plugin" you want in your editor
  const myPlugin = (e) => {
    var insertActions = [{
      text: 'Heading 1',
      icon: 'h1',
      action: () => {
        e.execCommand('mceInsertContent', false, '<h1>Heading 1</h1>');
        e.selection.select(e.selection.getNode());
      }
    }];

    e.ui.registry.addAutocompleter(pluginName, {
      ch: '/',
      minChars: 0,
      columns: 1,
      fetch: (pattern) => {
        const matchedActions = insertActions.filter(action => action.type === 'separator' || action.text.toLowerCase().indexOf(pattern.toLowerCase()) !== -1);
        return new Promise((resolve) => {
          const results = matchedActions.map(action => ({
            meta: action,
            text: action.text,
            icon: action.icon,
            value: action.text,
            type: action.type
          }));
          resolve(results);
        });
      },
      onAction: (api, rng, action, meta) => {
        e.selection.setRng(rng);
        e.execCommand('Delete');
        meta.action();
        api.hide();
      }
    });
    return {};
  };
  //  --End of plugin--

  let conf = {
    setup: (setupEditorThatWeDidntUseThisTimeBecauseWeUsedTheTinymceObjectInstead) => {
      // During the setup phase, the tinymce object should be already available
      console.log('tinymce object: ', tinymce);
      // This should make the plugin available to every editor created from this TinyMCE instance
      tinymce.PluginManager.add(pluginName, myPlugin);
    },
    toolbar: 'undo redo bold italic numlist',
    plugins: `${pluginName} lists`

  };

  let editorValue = '<h1>Hello</h1><p>I am an inline editor</p>';
  let inline = true;

  // Because the first editor setup added the plugin to the tinymce object, this editor will have access to that plugin
  let secondConf = {
    plugins: `${pluginName}`
  }
</script>

<main>
	<h1>Hello {name}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>
  <Editor {conf} />
  <p>Following is an inline editor</p>
  <Editor {inline} bind:value={editorValue} cssClass={"inlineEditor"} conf={secondConf}/>
  <div>{@html editorValue}</div>
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

  :global(.inlineEditor) {
    border: dashed #ff3e00;
  }

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
```

@dmccallie there are multiple ways to get an inline editor. The closest thing to running `init` would be using the `conf` property as it takes an initialization object the same way the pure editor would. However, the wrapper comes with an auxiliary `inline` property that you can use instead. I made an inline editor in the same example using `let inline = true;` and then `<Editor {inline} />` but you can do `<Editor inline={true} />` just the same way. This should be documented here: [https://www.tiny.cloud/docs/integrations/svelte/#exampleusinginline](https://www.tiny.cloud/docs/integrations/svelte/#exampleusinginline)

Hope this helps

**Comment by deshartman** [comment]
@jscasca thank you so much for making the time to explain this and build the example. I can see now how this works.
