### ISSUE TITLE
Add missing exports conditions

### ISSUE THREAD

**Issue by laxadev** [tinymce/tinymce-svelte#50]
You can find more information about this here https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by ptrxyz** [comment]
With latest versions of Svelte, this is required and throws nasty warnings all day long.


The fix is super simple, simply add the `exports` object to the `package.json` and it's all good:

```json
...
"svelte": "dist/index.js",
"exports": {
    ".": {
        "svelte": "./dist/index.js"
    }
},
...
```

**Comment by ptrxyz** [comment]
Added PR: #52
