### ISSUE TITLE
ReadOnly mod does not work

### ISSUE THREAD

**Issue by michalss** [tinymce/tinymce-svelte#60]
Hi,

Can you please help me out i need to make readonly work, but i did try everyting i could nothing really works. readonly: true, mode: "readonly" or  disabled=false. Simple that config opition does not work. 

My goal is to make tiny as simple div container without posibility to edit it

thx

**Comment by danoaky-tiny** [comment]
The property you're looking for is `disabled`, see: https://www.tiny.cloud/docs/tinymce/latest/svelte-ref/#disabled

Also see the storybook with the disabled prop in use: https://tinymce.github.io/tinymce-svelte/?path=/story/editor--disabling
